# Generated by Django 6.0.5 on 2026-07-18 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, default='TEMP', help_text='Manual Registration Number', max_length=50, null=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age_months', models.PositiveIntegerField(default=0, help_text='Months (0-11)', validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('id_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Pre-existing conditions like BP, Diabetes, etc.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('referred_by', models.CharField(blank=True, default='Self', help_text='Referring doctor if external or lab direct', max_length=255, null=True)),
                ('assigned_role', models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('DOCTOR', 'Doctor'), ('LAB', 'Lab'), ('PHARMACY', 'Pharmacy'), ('BILLING', 'Billing'), ('CASUALTY', 'Casualty')], default='DOCTOR', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('vitals', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
