# Generated by Django 4.2.30 on 2026-08-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_close_duplicate_active_visits'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_PROGRESS'])), fields=('patient',), name='one_active_visit_per_patient'),
        ),
    ]
