# Generated by Django 4.2.30 on 2026-09-01 13:35
# Hand-edited: AddIndex -> AddIndexConcurrently so these builds don't lock
# writes to `patients`/`visits` in production. CONCURRENTLY requires each
# index to run outside a transaction, hence atomic = False.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('patients', '0005_add_one_active_visit_constraint'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patients_pa_created_542792_idx'),
        ),
        AddIndexConcurrently(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'),
        ),
        AddIndexConcurrently(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'),
        ),
        AddIndexConcurrently(
            model_name='patient',
            index=models.Index(fields=['registration_number'], name='patients_pa_registr_040bbc_idx'),
        ),
        AddIndexConcurrently(
            model_name='visit',
            index=models.Index(fields=['created_at'], name='patients_vi_created_05576e_idx'),
        ),
        AddIndexConcurrently(
            model_name='visit',
            index=models.Index(fields=['updated_at'], name='patients_vi_updated_7bdcb5_idx'),
        ),
        AddIndexConcurrently(
            model_name='visit',
            index=models.Index(fields=['patient', 'status'], name='patients_vi_patient_9688b2_idx'),
        ),
        AddIndexConcurrently(
            model_name='visit',
            index=models.Index(fields=['assigned_role', 'status'], name='patients_vi_assigne_e48d47_idx'),
        ),
    ]
