# Generated by Django 5.2.4 on 2026-07-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_age_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Pre-existing conditions like BP, Diabetes, etc.', null=True),
        ),
    ]
