# Generated by Django 6.0.5 on 2026-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='referred_by',
            field=models.CharField(blank=True, default='Self', help_text='Referring doctor if external or lab direct', max_length=255, null=True),
        ),
    ]
