# Generated by Django 5.2.4 on 2026-05-01 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_code', models.CharField(max_length=100, unique=True)),
                ('operation_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price_per_unit__gte', 0)), name='price_per_unit_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('balance_qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory Balances',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance_qty__gte', 0)), name='balance_qty_non_negative'), models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size_balance')],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('amount_earned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='api.employee')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='api.operation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='api.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_greater_than_zero'), models.UniqueConstraint(fields=('work_date', 'employee', 'product', 'operation', 'size'), name='unique_production_log_entry')],
            },
        ),
    ]
