# Generated by Django 5.2.4 on 2026-05-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionlog',
            name='quantity_greater_than_zero',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='productionlog',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_positive'),
        ),
    ]
