# Generated by Django 5.2.4 on 2026-05-01 08:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_productionlog_quantity_greater_than_zero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_size_name', message='Size name must be alphanumeric (no special symbols).', regex='^[a-zA-Z0-9]*$')])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Size',
                'ordering': ['display_order', 'size_name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.designation'),
        ),
        migrations.AlterField(
            model_name='inventorybalance',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='api.productsize'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='api.productsize'),
        ),
    ]
