# Generated by Django 5.2.4 on 2026-05-08 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_address_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('piece_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_operations', to='api.operation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_operations', to='api.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('piece_rate__gte', 0)), name='piece_rate_non_negative'), models.UniqueConstraint(fields=('product', 'operation'), name='unique_product_operation')],
            },
        ),
    ]
