# Generated by Django 5.2.4 on 2026-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
