# Generated by Django 5.2.4 on 2026-05-08 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_operation_operation_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorybalance',
            name='unique_product_size_balance',
        ),
        migrations.RemoveConstraint(
            model_name='productionlog',
            name='unique_production_log_entry',
        ),
        migrations.RemoveField(
            model_name='inventorybalance',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='size',
        ),
        migrations.AlterField(
            model_name='inventorybalance',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balance', to='api.product'),
        ),
        migrations.AddConstraint(
            model_name='productionlog',
            constraint=models.UniqueConstraint(fields=('work_date', 'employee', 'product', 'operation'), name='unique_production_log_entry'),
        ),
    ]
