# Generated by Django 5.2.4 on 2026-05-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_inventorybalance_unique_product_size_balance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionlog',
            name='unique_production_log_entry',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='size',
            field=models.ForeignKey(default='e6b4476f-224b-4eeb-a548-cbe9b09c6b5e', on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='api.productsize'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='productionlog',
            constraint=models.UniqueConstraint(fields=('work_date', 'employee', 'product', 'operation', 'size'), name='unique_production_log_entry'),
        ),
    ]
