# Generated by Django 5.2.4 on 2026-05-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_productionlog_unique_production_log_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybalance',
            name='operation',
            field=models.ForeignKey(default='d0bcd89d-e911-44a3-be67-0a79dbdb724a', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='api.operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='size',
            field=models.ForeignKey(default='e6b4476f-224b-4eeb-a548-cbe9b09c6b5e', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='api.productsize'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorybalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='api.product'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'operation'), name='unique_product_size_operation_inventory'),
        ),
    ]
