# Generated by Django 5.2.4 on 2026-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_inventorybalance_operation_inventorybalance_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_final_operation',
            field=models.BooleanField(default=False, help_text='If True, completing this operation adds to the finished goods inventory.'),
        ),
    ]
