# Generated by Django 5.2.4 on 2026-05-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_operation_is_final_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='is_final_operation',
        ),
    ]
