# Generated by Django 5.2.4 on 2026-05-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_operation_is_final_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybalance',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='api.operation'),
        ),
    ]
