# Generated by Django 5.2.4 on 2026-05-15 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_inventorybalance_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('out_date', models.DateField(auto_now_add=True)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='api.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='api.productsize')),
            ],
            options={
                'verbose_name_plural': 'Stock Outs',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_out_quantity_positive')],
            },
        ),
    ]
