# Generated by Django 5.2.4 on 2026-05-15 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_employee_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_stocks', to='api.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_stocks', to='api.productsize')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size_master_stock')],
            },
        ),
    ]
