# Generated by Django 5.2.4 on 2026-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
