# Generated by Django 5.2.4 on 2026-05-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_productionlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
