# Generated by Django 5.2.4 on 2026-06-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_productionlog_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionlog',
            name='unique_production_log_entry',
        ),
    ]
