# Generated by Django 5.2.4 on 2026-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_productionlog_unique_production_log_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/photos/'),
        ),
    ]
