# Generated by Django 6.0.5 on 2026-07-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
