# Generated by Django 4.2.30 on 2026-09-01 12:20
# Hand-edited: AddIndex -> AddIndexConcurrently so these builds don't lock
# writes to `billing` tables in production. CONCURRENTLY requires each
# index to run outside a transaction, hence atomic = False.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('billing', '0003_alter_invoiceitem_item_id'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='billing_inv_created_1e16da_idx'),
        ),
        AddIndexConcurrently(
            model_name='invoice',
            index=models.Index(fields=['payment_status', 'created_at'], name='billing_inv_payment_8954a6_idx'),
        ),
        AddIndexConcurrently(
            model_name='invoiceitem',
            index=models.Index(fields=['created_at'], name='billing_inv_created_b622a8_idx'),
        ),
        AddIndexConcurrently(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'dept'], name='billing_inv_invoice_d3e43d_idx'),
        ),
        AddIndexConcurrently(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='billing_pay_created_d70ee8_idx'),
        ),
    ]
