# Generated by Django 6.0.5 on 2026-07-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_invoice_discount_amount_invoice_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
