# Generated by Django 6.0.5 on 2026-07-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casualty', '0002_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualtymedicine',
            name='med_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacystock'),
        ),
        migrations.AddField(
            model_name='casualtymedicine',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_medicines', to='patients.visit'),
        ),
        migrations.AddField(
            model_name='casualtyobservation',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_observations', to='patients.visit'),
        ),
        migrations.AddField(
            model_name='casualtyservice',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_services', to='patients.visit'),
        ),
        migrations.AddField(
            model_name='casualtyservice',
            name='service_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casualty.casualtyservicedefinition'),
        ),
    ]
