# Generated by Django 4.2.30 on 2026-09-01 12:20
# Hand-edited: AddIndex -> AddIndexConcurrently so these builds don't lock
# writes to `casualty` tables in production. CONCURRENTLY requires each
# index to run outside a transaction, hence atomic = False.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('casualty', '0003_initial'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='casualtylog',
            index=models.Index(fields=['created_at'], name='casualty_ca_created_f66263_idx'),
        ),
        AddIndexConcurrently(
            model_name='casualtymedicine',
            index=models.Index(fields=['created_at'], name='casualty_ca_created_95a4bd_idx'),
        ),
        AddIndexConcurrently(
            model_name='casualtyobservation',
            index=models.Index(fields=['created_at'], name='casualty_ca_created_a62aa5_idx'),
        ),
        AddIndexConcurrently(
            model_name='casualtyobservation',
            index=models.Index(fields=['visit', 'is_active'], name='casualty_ca_visit_i_5d7f75_idx'),
        ),
        AddIndexConcurrently(
            model_name='casualtyservice',
            index=models.Index(fields=['created_at'], name='casualty_ca_created_7a6d07_idx'),
        ),
        AddIndexConcurrently(
            model_name='casualtyservice',
            index=models.Index(fields=['visit', 'status'], name='casualty_ca_visit_i_37b670_idx'),
        ),
    ]
