# Generated by Django 6.0.5 on 2026-07-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('complaints', models.TextField(blank=True, default='')),
                ('examination', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('prescription', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('lab_referral_details', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
