# Generated by Django 4.2.30 on 2026-09-01 12:20
# Hand-edited: AddIndex -> AddIndexConcurrently so this build doesn't lock
# writes to `doctornote` in production. CONCURRENTLY requires the index to
# run outside a transaction, hence atomic = False.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('medical', '0002_initial'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='doctornote',
            index=models.Index(fields=['created_at'], name='medical_doc_created_039d6f_idx'),
        ),
    ]
