# Generated by Django 4.2.30 on 2026-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_doctornote_medical_doc_created_039d6f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
