# Generated by Django 6.0.5 on 2026-07-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_delete_casualtylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornote',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
