# Generated by Django 6.0.5 on 2026-07-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_allow_blank_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='complaints',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='examination',
            field=models.TextField(blank=True, default=''),
        ),
    ]
