# Generated by Django 4.2.30 on 2026-09-01 12:20
# Hand-edited: AddIndex -> AddIndexConcurrently for the actual index build,
# which must run outside a transaction, hence atomic = False.
# AlterModelOptions is a Django-state-only change (the model previously had
# no explicit Meta) -- it touches no database schema, so it's left as a
# regular operation and runs fine alongside atomic = False.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        AddIndexConcurrently(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'),
        ),
    ]
