# Generated by Django 6.0.5 on 2026-07-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcharge',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_charges', to='patients.visit'),
        ),
        migrations.AddField(
            model_name='labbatch',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='lab.labinventory'),
        ),
        migrations.AddField(
            model_name='labinventorylog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab.labinventory'),
        ),
    ]
