# Generated by Django 6.0.5 on 2026-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcharge',
            name='notes',
            field=models.TextField(blank=True, help_text='Overall notes for the lab test', null=True),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='is_heading',
            field=models.BooleanField(default=False, help_text='If True, this acts as a subheading (unit/range ignored)'),
        ),
    ]
