# Generated by Django 6.0.5 on 2026-07-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_labcharge_notes_labtestparameter_is_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, help_text='Common description/interpretation for the whole test', null=True),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='description',
            field=models.TextField(blank=True, help_text='Description box under this parameter', null=True),
        ),
    ]
