# Generated by Django 6.0.5 on 2026-07-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_labtest_description_labtestparameter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcharge',
            name='parent_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_charges', to='lab.labcharge'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='package_tests',
            field=models.ManyToManyField(blank=True, related_name='packages', to='lab.labtest'),
        ),
    ]
