# Generated by Django 4.2.30 on 2026-08-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_labcharge_parent_charge_labtest_is_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='lab.labsupplier'),
        ),
        migrations.AlterField(
            model_name='labinventory',
            name='unit',
            field=models.CharField(choices=[('units', 'Units'), ('ml', 'ml (millilitre)'), ('litre', 'Litre'), ('strips', 'Strips'), ('tests', 'Tests'), ('vials', 'Vials'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('packs', 'Packs'), ('pieces', 'Pieces'), ('grams', 'Grams')], default='units', max_length=50),
        ),
    ]
