# Generated by Django 4.2.30 on 2026-08-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_purchaseitem_content'),
        ('lab', '0007_add_supplier_and_unit_choices_to_labinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_batches', to='pharmacy.supplier'),
        ),
        migrations.AlterField(
            model_name='labinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_inventory_items', to='pharmacy.supplier'),
        ),
        migrations.AlterField(
            model_name='labpurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_purchases', to='pharmacy.supplier'),
        ),
    ]
