# Generated by Django 4.2.30 on 2026-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_use_shared_supplier_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbatch',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='labinventory',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='labinventorylog',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='labtestrequireditem',
            name='qty_per_test',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
