# Generated by Django 4.2.30 on 2026-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_decimal_quantities_for_liquid_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbatch',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='labbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
