# Generated by Django 4.2.30 on 2026-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_optional_batch_no_and_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinventory',
            name='items_per_pack',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='labpurchaseitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='labpurchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labpurchaseitem',
            name='free_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='labpurchaseitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
