# Generated by Django 4.2.30 on 2026-09-01 13:35
# Hand-edited: AddIndex -> AddIndexConcurrently so these builds don't lock
# writes to `lab` tables in production. CONCURRENTLY requires each index to
# run outside a transaction, hence atomic = False.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('lab', '0011_decimal_purchase_qty_optional_expiry'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='labbatch',
            index=models.Index(fields=['inventory_item', 'expiry_date'], name='lab_labbatc_invento_7a951b_idx'),
        ),
        AddIndexConcurrently(
            model_name='labcharge',
            index=models.Index(fields=['created_at'], name='lab_labchar_created_2843a7_idx'),
        ),
        AddIndexConcurrently(
            model_name='labcharge',
            index=models.Index(fields=['visit', 'status'], name='lab_labchar_visit_i_13060d_idx'),
        ),
        AddIndexConcurrently(
            model_name='labcharge',
            index=models.Index(fields=['test_name'], name='lab_labchar_test_na_3f6569_idx'),
        ),
        AddIndexConcurrently(
            model_name='labinventory',
            index=models.Index(fields=['item_name'], name='lab_labinve_item_na_113d84_idx'),
        ),
        AddIndexConcurrently(
            model_name='labpurchase',
            index=models.Index(fields=['invoice_date'], name='lab_labpurc_invoice_db583c_idx'),
        ),
        AddIndexConcurrently(
            model_name='labtest',
            index=models.Index(fields=['name'], name='lab_labtest_name_b73df5_idx'),
        ),
    ]
