# Generated by Django 5.2.4 on 2026-07-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_labinventory_items_per_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcharge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFICATION', 'Pending Verification'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
