# Generated by Django 6.0.5 on 2026-07-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_alter_labcharge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcharge',
            name='drawn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labcharge',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labcharge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DRAWN', 'Sample Drawn'), ('RECEIVED', 'Sample Received'), ('VERIFICATION', 'Pending Verification'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
