# Generated by Django 6.0.5 on 2026-07-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyreturn',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacyreturnitem',
            name='return_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacyreturn'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.visit'),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pharmacy.pharmacysale'),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacysale'),
        ),
        migrations.AddField(
            model_name='pharmacyreturnitem',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='pharmacy.pharmacysaleitem'),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='med_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacystock'),
        ),
        migrations.AddField(
            model_name='pharmacyreturnitem',
            name='med_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacystock'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier'),
        ),
        migrations.AddConstraint(
            model_name='pharmacystock',
            constraint=models.UniqueConstraint(fields=('name', 'batch_no'), name='unique_stock_name_batch'),
        ),
    ]
