# Generated by Django 6.0.5 on 2026-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacystock',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('SYRUP', 'Syrup'), ('DROP', 'Drop'), ('INJECTION', 'Injection'), ('GEL', 'Gel'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('OTHER', 'Other'), ('MEDICINE', 'Medicine')], default='TABLET', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('SYRUP', 'Syrup'), ('DROP', 'Drop'), ('INJECTION', 'Injection'), ('GEL', 'Gel'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('OTHER', 'Other'), ('MEDICINE', 'Medicine')], default='TABLET', max_length=20),
        ),
    ]
