# Generated by Django 6.0.5 on 2026-07-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacystock_medicine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
