# Generated by Django 6.0.5 on 2026-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_pharmacystock_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
