# Generated by Django 4.2.30 on 2026-08-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_purchaseitem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacystock',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('DROP', 'Drop'), ('INJECTION', 'Injection'), ('GEL', 'Gel'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('OTHER', 'Other'), ('MEDICINE', 'Medicine')], default='TABLET', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('DROP', 'Drop'), ('INJECTION', 'Injection'), ('GEL', 'Gel'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('OTHER', 'Other'), ('MEDICINE', 'Medicine')], default='TABLET', max_length=20),
        ),
    ]
