# Generated by Django 4.2.30 on 2026-09-01 13:35
# Hand-edited: AddIndex -> AddIndexConcurrently so these builds don't lock
# writes to `pharmacy` tables in production (PharmacyStock especially is
# written on every sale). CONCURRENTLY requires each index to run outside a
# transaction, hence atomic = False.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('pharmacy', '0006_add_capsule_medicine_type'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='pharmacysale',
            index=models.Index(fields=['sale_date'], name='pharmacy_ph_sale_da_801d95_idx'),
        ),
        AddIndexConcurrently(
            model_name='pharmacysale',
            index=models.Index(fields=['patient', 'payment_status'], name='pharmacy_ph_patient_5d2dbf_idx'),
        ),
        AddIndexConcurrently(
            model_name='pharmacysaleitem',
            index=models.Index(fields=['created_at'], name='pharmacy_ph_created_bc3420_idx'),
        ),
        AddIndexConcurrently(
            model_name='pharmacystock',
            index=models.Index(fields=['is_deleted', 'name'], name='pharmacy_ph_is_dele_a98378_idx'),
        ),
        AddIndexConcurrently(
            model_name='pharmacystock',
            index=models.Index(fields=['name', 'expiry_date'], name='pharmacy_ph_name_b76aeb_idx'),
        ),
        AddIndexConcurrently(
            model_name='pharmacystock',
            index=models.Index(fields=['barcode'], name='pharmacy_ph_barcode_28c605_idx'),
        ),
        AddIndexConcurrently(
            model_name='pharmacystock',
            index=models.Index(fields=['expiry_date'], name='pharmacy_ph_expiry__9119f4_idx'),
        ),
        AddIndexConcurrently(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_date'], name='pharmacy_pu_invoice_3c84cd_idx'),
        ),
        AddIndexConcurrently(
            model_name='purchaseitem',
            index=models.Index(fields=['created_at'], name='pharmacy_pu_created_e6c9b0_idx'),
        ),
        AddIndexConcurrently(
            model_name='supplier',
            index=models.Index(fields=['supplier_name'], name='pharmacy_su_supplie_ca7f1a_idx'),
        ),
    ]
