# Generated by Django 6.0.5 on 2026-07-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_pharmacystock_category_purchaseinvoice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='timing',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
